// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrbanEcho.Reporting;

#nullable disable

namespace UrbanEcho.Migrations
{
    [DbContext(typeof(ReportContext))]
    [Migration("20260319150006_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("UrbanEcho.Models.Report.IntersectionReport", b =>
                {
                    b.Property<int>("IntersectionReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("IntersectionReportId");

                    b.ToTable("IntersectionReport");
                });

            modelBuilder.Entity("UrbanEcho.Models.Report.IntersectionReportModel", b =>
                {
                    b.Property<int>("IntersectionReportModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AverageSpeed")
                        .HasColumnType("REAL");

                    b.Property<double>("AverageTimeSpent")
                        .HasColumnType("REAL");

                    b.Property<double>("AverageWaitTime")
                        .HasColumnType("REAL");

                    b.Property<string>("IntersectionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("IntersectionReportId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Lat")
                        .HasColumnType("REAL");

                    b.Property<double>("Lon")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalTimeSpent")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalWaitTime")
                        .HasColumnType("REAL");

                    b.Property<int>("VehicleCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("IntersectionReportModelId");

                    b.HasIndex("IntersectionReportId");

                    b.ToTable("IntersectionReportModel");
                });

            modelBuilder.Entity("UrbanEcho.Models.Report.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntersectionReportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoadEdgeReportId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReportId");

                    b.HasIndex("IntersectionReportId");

                    b.HasIndex("RoadEdgeReportId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("UrbanEcho.Models.Report.RoadEdgeReport", b =>
                {
                    b.Property<int>("RoadEdgeReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("RoadEdgeReportId");

                    b.ToTable("RoadEdgeReport");
                });

            modelBuilder.Entity("UrbanEcho.Models.Report.RoadEdgeReportModel", b =>
                {
                    b.Property<int>("RoadEdgeReportModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AverageSpeed")
                        .HasColumnType("REAL");

                    b.Property<double>("AverageTimeSpent")
                        .HasColumnType("REAL");

                    b.Property<double>("AverageWaitTime")
                        .HasColumnType("REAL");

                    b.Property<int?>("IntersectionReportModelId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Lat")
                        .HasColumnType("REAL");

                    b.Property<double>("Lon")
                        .HasColumnType("REAL");

                    b.Property<int?>("RoadEdgeReportId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalTimeSpent")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalWaitTime")
                        .HasColumnType("REAL");

                    b.Property<int>("VehicleCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoadEdgeReportModelId");

                    b.HasIndex("IntersectionReportModelId");

                    b.HasIndex("RoadEdgeReportId");

                    b.ToTable("RoadEdgeReportModel");
                });

            modelBuilder.Entity("UrbanEcho.Models.Report.IntersectionReportModel", b =>
                {
                    b.HasOne("UrbanEcho.Models.Report.IntersectionReport", null)
                        .WithMany("Intersections")
                        .HasForeignKey("IntersectionReportId");
                });

            modelBuilder.Entity("UrbanEcho.Models.Report.Report", b =>
                {
                    b.HasOne("UrbanEcho.Models.Report.IntersectionReport", "IntersectionReport")
                        .WithMany()
                        .HasForeignKey("IntersectionReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrbanEcho.Models.Report.RoadEdgeReport", "RoadEdgeReport")
                        .WithMany()
                        .HasForeignKey("RoadEdgeReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntersectionReport");

                    b.Navigation("RoadEdgeReport");
                });

            modelBuilder.Entity("UrbanEcho.Models.Report.RoadEdgeReportModel", b =>
                {
                    b.HasOne("UrbanEcho.Models.Report.IntersectionReportModel", null)
                        .WithMany("Edges")
                        .HasForeignKey("IntersectionReportModelId");

                    b.HasOne("UrbanEcho.Models.Report.RoadEdgeReport", null)
                        .WithMany("Roads")
                        .HasForeignKey("RoadEdgeReportId");
                });

            modelBuilder.Entity("UrbanEcho.Models.Report.IntersectionReport", b =>
                {
                    b.Navigation("Intersections");
                });

            modelBuilder.Entity("UrbanEcho.Models.Report.IntersectionReportModel", b =>
                {
                    b.Navigation("Edges");
                });

            modelBuilder.Entity("UrbanEcho.Models.Report.RoadEdgeReport", b =>
                {
                    b.Navigation("Roads");
                });
#pragma warning restore 612, 618
        }
    }
}
